### ISSUE TITLE
add "release" so artifacts become downloadable again...

### ISSUE THREAD

**Issue by gernotstarke** [arc42/quality-requirements#11]

**Comment by aheusingfeld** [comment]
In which format should the scenarios be available for download?

**Comment by gernotstarke** [comment]
docx + pdf

**Comment by aheusingfeld** [comment]
Fixed for PDF with e65dce1417512931dc25bea864039f8fd42889ad

**Comment by aheusingfeld** [comment]
@gernotstarke do we really need the docx now that pdf works?

**Comment by aheusingfeld** [comment]
Done, see https://github.com/arc42/quality-requirements/releases/tag/v0.7.6
