### ISSUE TITLE
Include list of contributors

### ISSUE THREAD

**Issue by aheusingfeld** [arc42/quality-requirements#13]
In order to foster contributions IMHO it'd be great to automatically include the list the Github contributors in https://github.com/arc42/quality-requirements/blob/master/src/asciidoc/index.adoc

**Comment by rdmueller** [comment]
that might be a good build step for @docToolchain 😃

**Comment by aheusingfeld** [comment]
TheAPI is not as great as I thought it wouls be: https://developer.github.com/v3/repos/collaborators/

1. It requires authentication, ergo it can only be done server-side i.e. during the build
2. It provides login names and ids but neather real names nor email addresses 

I’m really questioning the usefulness of this scarce information and would rather update the list by hand. A little bit more than “I am Gernot Starke” (see contact page on aim42.org) would be nice 😜

**Comment by rdmueller** [comment]
hm. interesting to use the github api. I thought that git itself has some kind if stats command with which some info could be extracted... tigether with screenscraping, this could lead to results...
I'll keep this feature fo @docToolchain in mind...

**Comment by aheusingfeld** [comment]
Oh, of course, it’s always great to have someone looking at it from a different perspective. Thanks a lot, that should be easy and doable! And even contain real names and email addresses which are already public anyway. Great

**Comment by aheusingfeld** [comment]
If we simply use `git shortlog -se`, Gernot will get listed multiple times. If that's acceptable, we can go for it, otherwise we'd need to create a mapping for uniqueness 😒

```
$ git shortlog -se
     9  Alexander Heusingfeld <alexander.heusingfeld@innoq.com>
     1  Christoph Iserlohn <christoph.iserlohn@innoq.com>
     2  Dr. Gernot Starke <gs@gernotstarke.de>
     2  Gernot Starke <gs@gernotstarke.de>
    19  GernotStarke@MadZorg42 <gs@gernotstarke.de>
     9  GernotStarke@iMac <gs@gernotstarke.de>
     1  Oliver Tigges <oliver.tigges@lichtflut.de>
    24  gernots <gernot.starke@innoq.com>
```

**Comment by rdmueller** [comment]
different mail addresses are different users... 
this really can only be resolved through a manual mapping.
but the rest should be resolvable with the groovy `unique()` operator, shouldn't it?

**Comment by aheusingfeld** [comment]
Well, as we are on the shell, I‘d rather use awk, sed, perl or uniq but in general: yes, absolutely! 😉

My question was more whether we can directly use the output or @gernotstarke wants his users to be combined.

**Comment by gernotstarke** [comment]
imho this is a *very* futile and useless discussion, gentlemen: let's focus on content, please.

It'l take me approx 60seconds to create the contributor-list manually. Since now more than 3 years, this list has not changed a lot... therefore automation sounds like fun, but tweaking the auto-generated table will surely create more effort than manually adding Alex as new contributor :-)

just my 2 cents...
