### ISSUE TITLE
create release after github action build

### ISSUE THREAD

**Issue by gernotstarke** [arc42/quality-requirements#23]
da muss jemand was mit den github actions basteln :-)

**Comment by uniqueck** [comment]
Was soll denn genau passieren? Was soll den Released werden?

**Comment by gernotstarke** [comment]
der generierte HTML & pdf output, am liebsten auch ein docx, alles in einem zip zusammengepackt

**Comment by uniqueck** [comment]
Wie soll das Release ausgelöst werden? Tag setzen und pushen?

**Comment by gernotstarke** [comment]
das wäre super, danke

**Comment by uniqueck** [comment]
Soll auch ein changelog genutzt werden?

**Comment by uniqueck** [comment]
Das release sieht dann so aus auf der Github Release Seite. https://github.com/uniqueck/quality-requirements/releases
Ich habe allerdings das Tag vorhin gelöscht, daher ist der Status auf DRAFT.

**Comment by gernotstarke** [comment]
na das sieht doch prima aus! Danke für Deinen Support!
