### ISSUE TITLE
add pdf rendering

### ISSUE THREAD

**Issue by gernotstarke** [arc42/quality-requirements#4]
as this doc contains no images, pdf-rendering with asciidoctorj-pdf should work

**Comment by gernotstarke** [comment]
done - but the rendering engine issues errors (but converts just fine)

**Comment by gernotstarke** [comment]
https://www.mynethome.de/2016/11/16/asciidoctor-gradle-separate-tasks-for-pdf-and-html-output/

**Comment by aheusingfeld** [comment]
This is fixed with e65dce1417512931dc25bea864039f8fd42889ad
