### ISSUE TITLE
Download-Link

### ISSUE THREAD

**Issue by rdmueller** [arc42/quality-requirements#8]
Download-Link found in Readme.md does not work anymore:
https://github.com/arc42/quality-requirements/downloads/

"We’ve recently deprecated this downloads section (manually uploaded files).
Please read the blog post for more information."

=> https://github.com/blog/1302-goodbye-uploads

**Comment by gernotstarke** [comment]
Ralf, thx for notifying...

will switch over to [Releases](https://github.com/blog/1547-release-your-software)

**Comment by aheusingfeld** [comment]
Suggestion: Let's use https://github.com/asciidoctor/asciidoctor-gradle-examples/blob/master/asciidoc-to-pdf-example/build.gradle to at least enable PDF generation again. I'll take a look into how to generate this via travisCI and whether it is possible to auto-publish to Github Releases. 

According to the Github docs, I might need "Owner" permissions to enable releases though.

**Comment by gernotstarke** [comment]
yes, good idea. I just made you admin on github...

**Comment by aheusingfeld** [comment]
Whenever we create a tag in master now, the index.pdf will be added to the automatically created Release. See https://github.com/arc42/quality-requirements/releases/tag/v0.7.5
